import { Memory, MemoryCategory } from './memoryStore';

const START_MARKER = '<!-- copilot-memory:start -->';
const END_MARKER = '<!-- copilot-memory:end -->';

export function extractTags(content: string): string[] {
  const capitalized = [...content.matchAll(/\b[A-Z][a-zA-Z]{2,}\b/g)].map(m => m[0]);
  const techTerms = content.match(
    /\b(api|sdk|llm|asr|tts|vad|mcp|async|factory|strategy|repository|interface|pattern|auth|cache|queue|webhook)\b/gi
  ) ?? [];
  return [...new Set([...capitalized, ...techTerms].map(t => t.toLowerCase()))];
}

export function scoreMemory(memory: Memory, terms: string[]): number {
  return terms.filter(t =>
    memory.content.toLowerCase().includes(t) ||
    memory.tags.some(tag => tag.toLowerCase().includes(t))
  ).length;
}

const STOP_WORDS = new Set([
  'for', 'the', 'and', 'but', 'not', 'are', 'was', 'has', 'had',
  'its', 'with', 'that', 'this', 'from', 'into', 'when', 'then', 'than'
]);

export function parseSearchTerms(query: string): string[] {
  return query.toLowerCase().split(/\s+/).filter(t => t.length > 2 && !STOP_WORDS.has(t));
}

export function rankMemories(memories: Memory[], query: string, limit = 5): Memory[] {
  const terms = parseSearchTerms(query);
  if (terms.length === 0) {
    return [];
  }
  return memories
    .map(m => ({ memory: m, score: scoreMemory(m, terms) }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ memory }) => memory);
}

export function buildInstructionsBlock(memories: Memory[]): string {
  const byCategory = memories.reduce((acc, m) => {
    (acc[m.category] ??= []).push(m);
    return acc;
  }, {} as Record<MemoryCategory, Memory[]>);

  const sections = Object.entries(byCategory).map(([cat, mems]) => {
    const title = cat.charAt(0).toUpperCase() + cat.slice(1) + 's';
    const items = mems.map(m => `- ${m.content}`).join('\n');
    return `### ${title}\n${items}`;
  });

  return `${START_MARKER}\n## Project Memory (auto-generated by Copilot Memory)\n\n${sections.join('\n\n')}\n${END_MARKER}`;
}

export function mergeInstructions(existing: string, block: string): string {
  const start = existing.indexOf(START_MARKER);
  const end = existing.indexOf(END_MARKER);

  if (start !== -1 && end !== -1) {
    return (
      existing.slice(0, start).trimEnd() +
      '\n\n' +
      block +
      existing.slice(end + END_MARKER.length)
    );
  }

  return existing ? `${existing.trimEnd()}\n\n${block}` : block;
}

export function removeBlock(existing: string): string {
  const start = existing.indexOf(START_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (start !== -1 && end !== -1) {
    return (
      existing.slice(0, start).trimEnd() +
      existing.slice(end + END_MARKER.length)
    ).trim();
  }
  return existing;
}
